version: "3.9"

services:
  pg:
    image: postgres
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready"]
      interval: 7s
      timeout: 5s
      retries: 5
    networks:
      - app_network


  corsar-wallet:
    image: ivanpiankov/corsar-wallet:${COMMIT_TAG}
    container_name: corsar-wallet-backend
    environment:
      - ENABLE_MIGRATION=true
      - PG_HOST=pg
      - PG_PORT=5432
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DB=${PG_DB}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET_KEY}
    ports:
      - "8090:8000"
    depends_on:
      pg:
        condition: service_healthy
    networks:
      - app_network

volumes:
  db-data:

networks:
  app_network: