"""added name for wallet

Revision ID: 7a500ee114b2
Revises: defae579ae42
Create Date: 2023-03-26 15:28:59.898062

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7a500ee114b2"
down_revision = "defae579ae42"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("wallets", sa.Column("name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wallets", "name")
    # ### end Alembic commands ###
