"""added category tables

Revision ID: c34b09cf1243
Revises: cffa1ea9e32e
Create Date: 2023-04-15 19:19:16.841166

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c34b09cf1243"
down_revision = "cffa1ea9e32e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("category_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("icon", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("category_id"),
    )
    op.create_table(
        "subcategory",
        sa.Column("subcategory_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("icon", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.category_id"],
        ),
        sa.PrimaryKeyConstraint("subcategory_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subcategory")
    op.drop_table("category")
    # ### end Alembic commands ###
