"""renaming table with account

Revision ID: cffa1ea9e32e
Revises: 7a500ee114b2
Create Date: 2023-03-26 15:34:20.090068

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "cffa1ea9e32e"
down_revision = "7a500ee114b2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("account_type", sa.String(), nullable=False),
        sa.Column("balance", sa.DECIMAL(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("account_id"),
    )
    op.drop_table("wallets")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallets",
        sa.Column("wallet_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "wallet_type",
            postgresql.ENUM("CASH", "CARD", "SAVINGS_ACCOUNT", "DEPOSIT_ACCOUNT", name="account_types"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("balance", sa.NUMERIC(), autoincrement=False, nullable=False),
        sa.Column("currency", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("timezone('utc'::text, now())"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("timezone('utc'::text, now())"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], name="wallets_user_id_fkey"),
        sa.PrimaryKeyConstraint("wallet_id", name="wallets_pkey"),
    )
    op.drop_table("accounts")
    # ### end Alembic commands ###
